DROP MATERIALIZED VIEW IF EXISTS groups_sorted_by_affinity_index CASCADE;
DROP MATERIALIZED VIEW IF EXISTS periods CASCADE;
DROP MATERIALIZED VIEW IF EXISTS customers CASCADE;
DROP MATERIALIZED VIEW IF EXISTS purchase_history CASCADE;
DROP MATERIALIZED VIEW IF EXISTS groups CASCADE;
DROP MATERIALIZED VIEW IF EXISTS average_margin CASCADE;
