spring:
  liquibase:
    enabled: true
    contexts: test
  datasource:
    url: ${URL_DB:jdbc:postgresql://localhost:5432/postgres}
    username: ${USERNAME_DB:postgres}
    password: ${PASSWORD_DB:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: validate

server.port: ${SERVER_PORT:8081}